[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Fork settings for testing
[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
